### ISSUE TITLE
GPU Accelerated Darknet

### ISSUE THREAD

**Issue by innerop** [zoranzhao/DeepThings#3]
Hi again!

I have a bunch of edge devices with CUDA 9  (GPU) and ARM64 and I have successfully built Darknet/Yolo2 with GPU support.

Can I try out this project without modification? Will it simply use the GPU in this case if it doesn't detect NNPACk or do I need to make some changes?

Thank you,

**Comment by zoranzhao** [comment]
Hi innerop, 
Inference using GPU/CUDNN library is implemented in Darknet, and is controlled by GPU/CUDNN macros. You can build your Darknet in such way, or you can modify the top level Makefile in DeepThings to turn on the GPU and CUDNN options in Darknet:

     GPU=1
     CUDNN=1
     $(DARKNETLIB):
                $(MAKE) -C $(DARKNET) CUDNN=$(CUDNN) GPU=$(GPU) all

DeepThings doesn't require any specific inference features from libraries. So using GPU, NNPACK or whatever you need will still be compatible with current DeepThings implementation.
